name: Publish Extension

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v0.0.2, v1.0.0, etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Setup virtual display for VS Code tests
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        
    - name: Run tests
      run: xvfb-run -a yarn test
      
    - name: Package extension
      run: yarn run package
      
    - name: Publish to VS Code Marketplace
      run: npx @vscode/vsce publish --pat ${{ secrets.VSCE_PAT }}
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ## Changes in ${{ github.ref_name }}
          
          See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for detailed changes.
          
          ## Installation
          
          Install directly from VS Code Marketplace:
          ```
          ext install johuang.mongodb-objectid-parser
          ```
          
          Or search for "MongoDB ObjectId Parser" in VS Code Extensions.
        draft: false
        prerelease: false
